version: 2.1

orbs:
  psyplot: psyplot/psyplot-ci-orb@1.5.19
  mattermost-plugin-notify: nathanaelhoun/mattermost-plugin-notify@1.2.0

executors:
  default: psyplot/default
  macos: psyplot/macos

parameters:
  unit-test-executor:
    description: Executor for the unit tests. Can be default or macos
    type: string
    default: default
  deploy-release:
    description: Deploy the comment as a new release to github and pypi
    type: boolean
    default: false
  test-matplotlib-3_3:
    description: Run the test suite for matplotlib 3.3
    type: boolean
    default: true
  test-matplotlib-latest:
    description: Run the test suite for the latest version of matplotlib
    type: boolean
    default: true
  parallelism:
    description: How many parallel jobs to execute
    type: integer
    default: 2
  build_docs:
    description: Build the documentation
    type: boolean
    default: true


workflows:
  build-and-test:
    unless: << pipeline.parameters.deploy-release >>
    jobs:
      - psyplot/install-and-build:
          name: install
          exec_environment: << pipeline.parameters.unit-test-executor >>
          setup_env: true
          build_args: "--no-test"
          build_docs: << pipeline.parameters.build_docs >>
          env_packages: pytest-cov dask psyplot-gui statsmodels netcdf4 seaborn pytest-qt
      - psyplot/test-parallel:
          name: test-matplotlib-latest
          parallelism: << pipeline.parameters.parallelism >>
          run-job: << pipeline.parameters.test-matplotlib-latest >>
          build_refs: true
          requires:
            - install
      - psyplot/test-parallel:
          name: test-matplotlib-3.3
          parallelism: << pipeline.parameters.parallelism >>
          run-job: << pipeline.parameters.test-matplotlib-3_3 >>
          build_refs: true
          packages: matplotlib=3.3
          requires:
            - install
      - mattermost-plugin-notify/approval-notification:
          name: notify-deploy
          context: mattermost
          message: >-
            Hello @all! A workflow on https://app.circleci.com/pipelines/github/psyplot/psy-maps is awaiting your approval.
            Please check the uploaded docs and builds prior to approval.
          requires:
            - test-matplotlib-latest
            - test-matplotlib-3.3
      - hold-for-deploy:
          type: approval
          requires:
            - notify-deploy
      - psyplot/deploy-pkg:
          exec_environment: << pipeline.parameters.unit-test-executor >>
          context: anaconda
          requires:
            - hold-for-deploy
      - psyplot/deploy-docs:
          fingerprint: "b8:d6:d7:30:0a:74:2c:39:7b:45:0b:cd:bc:46:69:94"
          run-job: << pipeline.parameters.build_docs >>
          requires:
            - hold-for-deploy
          filters:
            branches:
              only: master
      - psyplot/trigger-release-workflow:
          context: trigger-release
          filters:
            branches:
              only: master
          requires:
            - psyplot/deploy-pkg
            - psyplot/deploy-docs
  publish-release:
    when: << pipeline.parameters.deploy-release >>
    jobs:
      - psyplot/create-tag:
          ssh-fingerprints: "b8:d6:d7:30:0a:74:2c:39:7b:45:0b:cd:bc:46:69:94"
          context: psyplot-admin
          user-name: psyplot-admin
          publish-release: true
          publish-version-tag: true
      - mattermost-plugin-notify/approval-notification:
          name: notify-release
          context: mattermost
          message: >-
            Hello @all! A new release has been created at https://github.com/psyplot/psy-maps/releases.
            Please review it carefully, publish it and approve the upload to pypi.
          requires:
            - psyplot/create-tag
      - hold-for-pypi:
          type: approval
          requires:
            - notify-release
      - psyplot/deploy-pypi:
          context: pypi
          requires:
            - hold-for-pypi
          filters:
            branches:
              only: master
