{% set name = "psy-maps" %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name|lower }}
  version: {{ data.get('version') }}

source:
  path: ../../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{ environ.get('CONDA_PY') }}{% if environ.get("BUILD_STR_END") %}_{{ environ.get("BUILD_STR_END") }}{% endif %}
  script: python -m pip install . --no-deps --ignore-installed -vvv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - psyplot >1.2.1
    - psy-simple
    - cartopy
    - scipy  # required for plotting with cartopy

test:
  imports:
    - psy_maps
    - psy_maps.plotters

  requires:
    - pytest
    - pytest-cov
    - codecov
    - dask
    - pyqt
    - xarray
    - netCDF4
    - seaborn
  source_files:
    - tests
  commands:
    - pytest -sv --cov=psy_maps --ref --ignore=tests/widgets
    - pytest -sv --cov-append --cov=psy_maps --ignore=tests/widgets
    - codecov

about:
  home: https://github.com/psyplot/psy-maps
  license: LGPL-3.0-only
  license_family: GPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: Psyplot plugin for visualization on a map

  description: |
    This psyplot plugin uses the cartopy package to visualize geo-referenced
    data on a map
  doc_url: http://psyplot.github.io/psy-maps
  dev_url: https://github.com/psyplot/psy-maps
